/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Files */
        get: operations["list_files_files_get"];
        put?: never;
        /**
         * Upload File
         * @description Multipart upload. Streams to a quarantine temp file, hashes,
         *     atomically renames to the live area, then enqueues profiling.
         */
        post: operations["upload_file_files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{file_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_files__file_id__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_file_files_post */
        Body_upload_file_files_post: {
            /** File */
            file: string;
        };
        /**
         * CardinalityClass
         * @enum {string}
         */
        CardinalityClass: "unique" | "low" | "high";
        /** ColumnProfile */
        ColumnProfile: {
            cardinality_class: components["schemas"]["CardinalityClass"];
            /** Currency Symbol */
            currency_symbol?: string | null;
            /** Date Format Candidates */
            date_format_candidates?: {
                [key: string]: number;
            } | null;
            /** Decimal Separator */
            decimal_separator?: string | null;
            /** Distinct Count */
            distinct_count: number;
            /**
             * Empty String Count
             * @default 0
             */
            empty_string_count: number;
            /** Fk Score */
            fk_score?: number | null;
            inferred_type: components["schemas"]["InferredType"];
            /** Leading Zero Ratio */
            leading_zero_ratio?: number | null;
            length_stats?: components["schemas"]["LengthStats"] | null;
            /** Max */
            max?: unknown | null;
            /** Min */
            min?: unknown | null;
            /** Name */
            name: string;
            /** Null Count */
            null_count: number;
            /** Null Rate */
            null_rate: number;
            /** Outlier Examples */
            outlier_examples?: unknown[];
            /** Pattern Hits */
            pattern_hits?: {
                [key: string]: number;
            };
            /**
             * Percent Unit
             * @default false
             */
            percent_unit: boolean;
            /** @default none */
            pii_class: components["schemas"]["PiiClass"];
            /** Pii Warnings */
            pii_warnings?: string[];
            /** Pk Score */
            pk_score: number;
            /** Position */
            position: number;
            quantiles?: components["schemas"]["Quantiles"] | null;
            /** Safe Name */
            safe_name: string;
            /** Sample Values */
            sample_values?: unknown[];
            /** Thousands Separator */
            thousands_separator?: string | null;
            /** Timezone Hints */
            timezone_hints?: {
                [key: string]: unknown;
            } | null;
            /** Top K */
            top_k?: components["schemas"]["TopKEntry"][] | null;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
            /** Unit Hint */
            unit_hint?: string | null;
        };
        /** FileListResponse */
        FileListResponse: {
            /** Items */
            items: components["schemas"]["FileSummary"][];
        };
        /** FileProfile */
        FileProfile: {
            /** Columns */
            columns: components["schemas"]["ColumnProfile"][];
            /** Delimiter */
            delimiter: string;
            /** Duplicate Row Count */
            duplicate_row_count: number;
            /** Encoding */
            encoding: string;
            /** Has Header */
            has_header: boolean;
            /** Omitted Columns */
            omitted_columns?: components["schemas"]["OmittedColumn"][];
            /** Profile Sha256 */
            profile_sha256: string;
            /**
             * Profile Version
             * @default v1
             */
            profile_version: string;
            /** Raw To Safe */
            raw_to_safe: {
                [key: string]: string;
            };
            /** Row Count */
            row_count: number;
            /** Source Sha256 */
            source_sha256: string;
        };
        /**
         * FileStatus
         * @enum {string}
         */
        FileStatus: "queued" | "profiling" | "profiled" | "failed";
        /** FileSummary */
        FileSummary: {
            /** Bytes */
            bytes: number;
            /** Id */
            id: number;
            /** Original Name */
            original_name: string;
            /** Profile Id */
            profile_id?: number | null;
            /** Source Sha256 */
            source_sha256: string;
            status: components["schemas"]["FileStatus"];
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InferredType
         * @enum {string}
         */
        InferredType: "int" | "float" | "bool" | "date" | "datetime" | "string" | "enum" | "json";
        /** LengthStats */
        LengthStats: {
            /** Max */
            max: number;
            /** Min */
            min: number;
            /** P50 */
            p50: number;
            /** P99 */
            p99: number;
        };
        /** OmittedColumn */
        OmittedColumn: {
            /** Distinct Count */
            distinct_count: number;
            inferred_type: components["schemas"]["InferredType"];
            /** Name */
            name: string;
            /** Null Rate */
            null_rate: number;
            /** Pk Score */
            pk_score: number;
            /** Position */
            position: number;
            /** Reason */
            reason: string;
            /** Safe Name */
            safe_name: string;
        };
        /**
         * PiiClass
         * @description High-confidence + best-effort classes. `name_like` / `address_like`
         *     are heuristics — they populate `pii_warnings`, never `pii_class`.
         * @enum {string}
         */
        PiiClass: "none" | "email" | "phone" | "ip" | "national_id" | "cc_like";
        /** Quantiles */
        Quantiles: {
            /** P1 */
            p1?: unknown | null;
            /** P50 */
            p50?: unknown | null;
            /** P99 */
            p99?: unknown | null;
        };
        /** TopKEntry */
        TopKEntry: {
            /** Count */
            count: number;
            /** Value */
            value: string | number | boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_files_files_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileListResponse"];
                };
            };
        };
    };
    upload_file_files_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_files__file_id__profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
